apiVersion: v1
kind: Service
metadata:
  name: master-service-lb
spec:
  type: LoadBalancer
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 8080 # Port on the container
