apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: terryureche/express-app:latest
          ports:
            - containerPort: 8080
